name: Mostrar nombre y apellidos

on:
  workflow_dispatch:
    inputs:
      nombre:
        description: "Introduce tu nombre"
        required: true
        default: "Nombre"
      apellidos:
        description: "Introduce tus apellidos"
        required: true
        default: "Apellidos"

jobs:
  imprimir:
    runs-on: windows-latest

    steps:
      - name: Mostrar nombre completo
        run: echo "Tu nombre es ${{ github.event.inputs.nombre }} ${{ github.event.inputs.apellidos }}"